# Generated by Django 3.0.6 on 2022-03-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
    ]
