# Generated by Django 3.0.6 on 2022-03-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_remove_place_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
